### ISSUE TITLE
Secret Key not a secret? 

### ISSUE THREAD

**Issue by Dayjo** [unsplash/unsplash-js#100]
Hello,

I have been trying to get my head around the terms and conditions, usage policy and the API docs but am finding some inconsistencies. 

According to the requirements when you create an app. The Secret Key must remain confidential;
![image](https://user-images.githubusercontent.com/1255512/58641474-2d4a0400-82f3-11e9-9d80-173e202a6bce.png)

However, in the documentation for this library, you state that we must use the secret key to initialise the client. This makes the secret key redundant and exposed to anyone who wants to fumble around the source code of the application. 

![image](http://c.dayjo.me/4ef96f0e3ee7/Image%202019-05-30%20at%203.54.30%20pm.png)

I'm unsure what the best practice is, but it is very concerning to include the secret key in the client side code, given that any user could take those credentials

Any advice would be great.

**Comment by tusharv** [comment]
As per https://help.unsplash.com/api-guidelines/unsplash-api-guidelines

> Your application’s Access Key  and Secret Key  must remain confidential. This means that they cannot be included in the client or made public. In most cases, this will require proxying the API through your own endpoint to sign the request with your keys.

So it's recommended to proxying the API through  our own endpoint.

**Comment by Dayjo** [comment]
So what's the purpose in having this as a JS client-side library if you can't even use it as such?

It relies on `fetch`, which is a browser / client based dependency, it even states on the readme the browser support for the library; 

![](http://c.dayjo.me/8b731ca5a3f3/Image%202019-06-03%20at%2010.43.52%20am.png)

To me, this reads as _"this is a browser-based client"_ which is very misleading.

**Comment by marcosnav** [comment]
Yes, the docs are fuzzy. I'm trying to making a client-side only app that fetches random photos from Unsplash and it's weird to have an official library focused on browsers support when that breaks the security stand point of keeping the API keys private.

I think the ACCESS KEY should be tied to a domain( or domains ) when applying for production to be used client-side and for any public endpoints. And, the SECRET KEY required when the request comes from an unidentified server and for advanced permissions actions.

**Comment by Dayjo** [comment]
@marcosnav I ended up having to implement an express server with a bit of hacky code that essentially proxy the requests that I was using. Horrible solution considering the purpose of this SDK but it kind of works, you may want to implement your own internal rate limiting or caching as part of doing this as well. Also not sure which SDK calls this does not support, currently I am only using Search, Get Photo and Download Photo.

```javascript
/**
 * unsplash-proxy.js
 */
const _get = require('lodash/get')
global.fetch = require('node-fetch')

// require syntax
const Unsplash = require('unsplash-js').default

module.exports = function (options) {
  return function (req, res, next) {
    // Grab the route after `/unsplash` i.e. /photos/getPhoto/12345
    let route = Object.values(req.params)[0]
    route = route.split('/').filter(String)

    let unsplash = new Unsplash({
      applicationId: options.access,
      secret: options.secret
    })

    // Make sure the route is only 2 items long
    let methodString = `${route[0]}.${route[1]}`

    // Check it is a method on the sdk
    let method = _get(unsplash, methodString)

    if (typeof method === 'function') {
      // Grab query variables
      let query = Object.values(req.query)
      if (route[2]) {
        query = [route[2]]
      }

      // The Post data if it's a post (downloadPhoto)
      if (req.method === 'POST') {
        query = [req.body]
      }

      // Call the unsplash method
      let prom = method.apply(unsplash, query)
      return prom.then(function (r) {
        // Copy the headers from the unsplash response
        for (let i in r.headers.raw()) {
          res.set(i, r.headers.get(i))
        }
        return r.json()
      })
        .then(function (r) {
        // Respond with the response
          res.status(200)
            .send(r)
        }).catch(function (e) {
          console.log('error', e)
        })
    }
  }
}
```
```javascript
/** 
* express-app.js
*/
const app = express()
const UnsplashProxy = require('./unsplash-proxy')

app.get('/unsplash*', UnsplashProxy({
  'appId': '',
  'access': '',
  'secret': ''
}))

app.post('/unsplash*', UnsplashProxy({
  'appId': '',
  'access': '',
  'secret': ''
}))
```

Then using `request` to hit the endpoint.
```js
/**
* Frontend App.js
*/
function get (apiUrl, parameters, bodyOnly) {
  return new Promise((resolve, reject) => {
    request.get(apiUrl).query(parameters).end((err, res) => {
      if (err) {
        return reject(err)
      }
      if (bodyOnly) {
        resolve(res.body)
      } else {
        resolve(res)
      }
    })
  })
}

get(`${unsplashEndpoint}/unsplash/search/photos`, {searchTerm: searchTerm, page: page, perPage: perPage})
.then((res) => { 
// Handle the result (Differently to the sdk though because of the toJSON stuff) 
})
```

Feel like I could potentially have just implemented direct API access via my own SDK without using this library in just as much time. 

@lukechesser at the very least update the docs to say `DO NOT USE THIS IN THE BROWSER IN PRODUCTION`?

**Comment by lukechesser** [comment]
Apologies to everyone on this. I'm totally with you that it isn't clear and needs to be updated.

The issue has been that this library is a bit out of date with some of the changes to the API guidelines. The credentials shouldn't be exposed in a browser as it leads to issues with the key being hijacked and used by other applications, which is an issue we've seen happen a lot.

I'll add a note to the README for now that makes that clearer. In the near future, we're going to look into updating this library to better be in line with the newer API Guidelines, as well as making using it client side while proxying through a server to sign the request easier to do and clearly documented.

**Comment by Dayjo** [comment]
Great, thanks @lukechesser 

If you ever need any testing for a client-side tokenised auth system let me know.

**Comment by vicente-s** [comment]
The demo mode doesn't require a token. It would be nice to document how to load this library via script tag and access Unsplash without an access token for prototyping purposes.

**Comment by lukechesser** [comment]
@vicente-s the readme states that you need to register as a developer to use the API + read the API guidelines.
