### ISSUE TITLE
Cannot specify timeout for API requests

### ISSUE THREAD

**Issue by lelikg** [unsplash/unsplash-js#106]
#### Steps to Reproduce
Issue an api request
-

#### Observed Behaviour
times out after default fetch timeout
-

#### Expected Behaviour
should be able to receive a timeout parameter via constructor
-

#### Technical Notes
Pull request https://github.com/unsplash/unsplash-js/pull/105

**Comment by lukechesser** [comment]
Added in #118 and will release in 6.0
