### ISSUE TITLE
Does API allow searching by location?

### ISSUE THREAD

**Issue by risoms** [unsplash/unsplash-js#107]
Is it possible to use the API to make a search by geographic parameters? For instance, city, state, latitude and longitude?

**Comment by lukechesser** [comment]
Not specifically. You can search for locations by keywords currently.

We may release a location specific endpoint, but it's not currently supported.

**Comment by robhawkes** [comment]
Would love to see this feature make it into Unsplash. There's a severe lack of options for publicly-accessible photography using spatial search. Even the most basic version of spatial search using distance from a point would be useful, and wouldn't require adopting a spatial database if whatever you're using doesn't already have spatial functionality.

I've a bunch of experience with spatial databases and functionality like this. Happy to help where I can as I think this feature would be amazing.

**Comment by lukechesser** [comment]
@robhawkes for sure. It's something we want to do.

One of the issues is that a photo doesn't necessarily represent its location just because it was shot near that location. i.e. I take a photo in NY of my coffee cup from Manhattan, that will rank higher for coordinates search than a photo shot in brooklyn of the skyline of NY.

But I guess that's the tradeoff here

**Comment by robhawkes** [comment]
Gotcha. I think in that case that's something you have to live with, that's the same with the Flickr API when it comes to searching by coordinates. At the end of the day the photo was shot at that location and so it makes sense to show it at that location on a map.

For my use-case your example is exactly the behaviour I would expect and desire. If you took a photo of the Manhattan skyline from Brooklyn then I'd want the photo to have the coordinates of the location you took the photo, not of the subject of the photo. I'm creating a location scout / trip planner app for photographers and so it's more important to have the photos placed at the location of the viewpoint — which happens to be the coordinates captured in the EXIF.

**Comment by lukechesser** [comment]
@robhawkes thanks for the context.

We want to work on this, but we've got a few other things we're heads down on right now. I'll try to update the issue with timing, but it likely won't be for at least another month or two

**Comment by manavo** [comment]
I’m guessing there’s still no timeframe for this @lukechesser? Just read through the docs and didn’t find any endpoints/params relating to this

Thanks

**Comment by lukechesser** [comment]
@manavo hey, still no movement on this. Would love to get to it, but we've been prioritizing other features right now. One day hopefully!

**Comment by manavo** [comment]
No worries, thanks for the quick update! Just wanted to make sure I wasn’t just missing it if it actually was done!

**Comment by brianacowles** [comment]
Bumping because this would be super helpful for a project I'm working on now. Only workaround I've found is to fetch based on keyword then filter using the `location` field in the response. Any ideas?

**Comment by leoherzog** [comment]
Still hoping for this someday!

**Comment by gbresciano** [comment]
@lukechesser please! this would be so helpful
