### ISSUE TITLE
Unexpected API output

### ISSUE THREAD

**Issue by csr** [unsplash/unsplash-js#109]
Hey, I wrote a Firebase cloud function to retrieve a list of photos, like this:

```
const unsplash = new Unsplash({
  applicationId: "XXXXX",
  secret: "XXXXXXXXXXXXXXXXXX"
});

exports.getPhotos = functions.https.onRequest((request, response) => {
  const promise = unsplash.photos.listPhotos(1, 10)
  .then(unsplash.toJson)
  .then(json => {
    response.status(200).send(CircularJSON.stringify(json));
    return;
  }).catch(error => {
    // handle the error
    console.log('Error:' + error);
    response.status(500).send(error);
    return;
  });
});
```

I'm getting a weird output out of that:

<img width="907" alt="Screen Shot 2019-08-28 at 3 49 19 PM" src="https://user-images.githubusercontent.com/10504710/63861563-6dc92480-c9ab-11e9-8652-db2758866367.png">

Any idea why? Also, just wanted to confirm that the application ID should be in a string and it's a 5 digit number.

Also, I'm using `CircularJSON` in `response.status(200).send(CircularJSON.stringify(json))` because if I were to do `response.status(200).send(json)` I would get `TypeError: Converting circular structure to JSON` so I wonder what does `unsplash.toJson` does.

Thanks!

**Comment by lukechesser** [comment]
I think this is happening because the `applicationId` should be equal to the `accessKey`. I'm fixing this to be clearer in #111
