### ISSUE TITLE
No Data in getRandomPhoto

### ISSUE THREAD

**Issue by MarkedWarrior** [unsplash/unsplash-js#120]
I'm on v6.0.0 and I'm trying to get random photos. Below is how I instantiate the unsplash object and how I query for random photos. 

Every time I make a request I get back {"size":0,"timeout":0}

I appreciate any help since I've been stuck on this for quite some time.

<img width="839" alt="Screen Shot 2019-10-23 at 8 20 07 PM" src="https://user-images.githubusercontent.com/15189068/67443838-884b0300-f5d4-11e9-850f-6c3aad2b08ee.png">

<img width="644" alt="Screen Shot 2019-10-23 at 8 25 37 PM" src="https://user-images.githubusercontent.com/15189068/67443842-8d0fb700-f5d4-11e9-99c9-95c5bad2e30c.png">

**Comment by lukechesser** [comment]
@MarkedWarrior I think you need to call `json()` on the resulting object, because you're getting back an instance from node-fetch. See their docs: https://github.com/bitinn/node-fetch#json

Note what happens when you do:

```
unsplash.users.profile('naoufal')
  .then(res => console.log(res));
// => logs an object

unsplash.users.profile('naoufal')
  .then(res => res.json())
  .then(json => console.log(json));
// => logs the actual JSON
```

**Comment by MarkedWarrior** [comment]
@lukechesser I can't believe that was the issue... thank you so much for your patience with me.
