### ISSUE TITLE
Allow to specify a `fetch` implementation via the module API

### ISSUE THREAD

**Issue by FezVrasta** [unsplash/unsplash-js#123]
Right now, we need to pollute the global scope with a `fetch` polyfill in order to use this module.

It'd be great if the library provided an explicit API to provide the required `fetch` polyfill, so that  an application doesn't need to pollute the global scope in order to make a single library happy.

A possible interface would look like this:

```js
// ES Modules syntax
import Unsplash from 'unsplash-js';
import fetchPolyfill from 'node-fetch';

const unsplash = new Unsplash({
  fetch: fetchPolyfill,
  accessKey: "{APP_ACCESS_KEY}"
});
```

**Comment by EdwardGoomba** [comment]
This would be nice - I literally just imported `node-fetch` in the API module to run it on node.
