### ISSUE TITLE
Adding per_page & page doesnt give proper result

### ISSUE THREAD

**Issue by schroef** [unsplash/unsplash-js#128]
#### Steps to Reproduce
Im looking into this Extension for illustrator which uses the API to find an image based on a query. I noticed the API was updated and ```/photos/search/``` was switched. However the attributes per_page and page doesn't seem to work. I cant find the proper order when using client_id in a path string in the documentation neither. All show single examples.

But using this path string ```https://api.unsplash.com/search/photos/?client_id=CLIENT_ID&query=kitten&per_page=1&page=1```
does not return a single image. 

-

#### Observed Behaviour
—
-

> _Image or video please._
![Screen Shot 2020-06-18 at 9 52 37 PM](https://user-images.githubusercontent.com/6923008/85088418-14d2b300-b1ae-11ea-974b-d414797352c1.png)

#### Expected Behaviour

-

#### Technical Notes
—
-

**Comment by lukechesser** [comment]
@schroef hm I can't reproduce:

```
curl --request GET \
  --url 'https://api.unsplash.com/search/photos?query=puppy&per_page=1&page=1&=&client_id=ACCESS_KEY' \
  --header 'content-type: application/json'
```

```
{
  "total": 3280,
  "total_pages": 3280,
  "results": [
    {
      "id": "TzjMd7i5WQI", ... 
    }
  ]
}
```

**Comment by schroef** [comment]
sorry for the late response!

I see you have the query formatted differently where client_id is at the end. Ill try that
