### ISSUE TITLE
collections.listCollections parameter "orderBy" not working

### ISSUE THREAD

**Issue by rochabianca** [unsplash/unsplash-js#133]
#### Steps to Reproduce

- Make an API call to collections.listCollections(1, 10, 'popular'), and then make the same call with 'latest' and 'oldest'

#### Observed Behaviour

- The results won't change

#### Expected Behaviour

- The collection's results changing accordly with the 'orderBy' parameter.

#### Technical Notes

- The param 'orderBy' seems to have been removed from the [unsplash API](https://unsplash.com/documentation#list-collections). In this case, it would be nice to remove the 'orderBy' parameter from the docs.

**Comment by samijaber** [comment]
closed in #143
