### ISSUE TITLE
Unsplash Stats Support Removed in v7?

### ISSUE THREAD

**Issue by jonathansousa** [unsplash/unsplash-js#152]
Has the ability to query global Unsplash stats been removed from the v7 unsplash-js library? In v6 you could call `unsplash.stats.total()` to get information about the full Unsplash photo library. The API endpoint still exists at `/stats/total`, according to the documentation, but there doesn't seem to be an option for querying that endpoint anymore. Is there another approach available?

**Comment by samijaber** [comment]
Hey @jonathansousa, as mentioned in https://github.com/unsplash/unsplash-js/blob/master/CHANGELOG.md#700 we removed API functions from this library that still exist on the Unsplash API. I just realized that I forgot to document the removal of `unsplash.stats.total()`, so I added that to the changelog. Sorry about that.

If you want to query endpoints that are not/no longer supported by this library, you will need to do so manually.
