### ISSUE TITLE
trackDownload: downloadLocation or download_location?

### ISSUE THREAD

**Issue by melounek** [unsplash/unsplash-js#153]
I just updated on `v7.0.1` and found that mismatch in your documentation and the real code.

In your readme is:

```javascript
unsplash.photos.trackDownload({
  downloadLocation: photo.links.downloadLocation,
});
```

But in the code the `downloadLocation` is `download_location`

I also found [this article](https://help.unsplash.com/en/articles/2511258-guideline-triggering-a-download), using `download_location`.

So I guess the Readme should be updated?

**Comment by samijaber** [comment]
Thanks for catching and filing the issue @melounek! The README had a typo here.
