### ISSUE TITLE
apiUrl issue

### ISSUE THREAD

**Issue by marconunnari** [unsplash/unsplash-js#154]
#### Steps to Reproduce

- Create a client in the browser as outlined in the readme:
```javascript
const unsplash = createApi({
  apiUrl: 'https://example.com/unsplash-proxy',
});
```

- Make a search:
```javascript
unsplash.search.getPhotos({
  query: 'cat',
  page: 1,
  perPage: 10,
  color: 'green',
  orientation: 'portrait',
});
```

#### Observed Behaviour

- The requests are sent to https://example.com/search/photos

#### Expected Behaviour

- The requests should be sent to https://example.com/unsplash/search/photos

#### Technical Notes

- I think the problem might be at https://github.com/unsplash/unsplash-js/blob/c4e57ca2324eb3a44d653207a880bc4581c766d9/src/helpers/url.ts#L17

**Comment by samijaber** [comment]
Addressed in #155. Published in 7.0.2 https://github.com/unsplash/unsplash-js/releases/tag/v7.0.2. Thanks for reporting!
