### ISSUE TITLE
apiUrl not respected in browser app

### ISSUE THREAD

**Issue by djfdev** [unsplash/unsplash-js#156]
#### Steps to Reproduce

1) Create an unsplash instance with proxy URL:

```js
const unsplash = createApi({
  apiUrl: 'http://localhost:4000/proxy'
})
```

2) Call some method

```js
unsplash.search.getPhotos({
  query: 'cats'
})
```

#### Observed Behaviour

HTTP request goes directly to Unsplash:

![image](https://user-images.githubusercontent.com/6677248/102548729-edcb4000-406f-11eb-9a6f-3b3d96e7690d.png)

#### Expected Behaviour

Request should go to my proxy at the specified `apiUrl`, not directly to unsplash.

#### Technical Notes

- v7.0.2
- Potentially related to fix for #154

**Comment by samijaber** [comment]
I can't reproduce. I tested in here https://stackblitz.com/edit/unsplash-js-example-api-url?file=index.tsx with the same `apiUrl` you provide, and I can see it in the logs that the request goes to the proxy URL and not to `api.unsplash.com`. If you can show me a way to reproduce then I can help.

**Comment by djfdev** [comment]
Apologies, I just updated Chrome and this is working as expected with my example code shared above. Thanks for taking a look.
