### ISSUE TITLE
Hey could you please add the  changes 

### ISSUE THREAD

**Issue by icsvishalmalji** [unsplash/unsplash-js#157]
#### Steps to Reproduce

-

#### Observed Behaviour
const unsplash = createApi({ }) doesn't work. 
-

> _Image or video please._

#### Expected Behaviour

- const unsplash = createApi.createApi({ }) this works

#### Technical Notes

-

**Comment by OliverJAsh** [comment]
@icsvishalmalji Please can you show us how you're importing `createApi`? You should be doing this:

```ts
import { createApi } from 'unsplash-js';
```

**Comment by icsvishalmalji** [comment]
> @icsvishalmalji Please can you show us how you're importing `createApi`? You should be doing this:
> 
> ```ts
> import { createApi } from 'unsplash-js';
> ```
> 
> or
> 
> ```ts
> const { createApi } = require('unsplash-js');
> ```
