### ISSUE TITLE
getRandom is always cast to Photo.Random but can return an array

### ISSUE THREAD

**Issue by LiamMartens** [unsplash/unsplash-js#163]
As per API spec - the random photo endpoint will return an array when passing `count` as a parameter.
This behavior is not reflected in TypeScript as the response is always `Photo.Random` regardless of parameters.

Ideally - the response would be `Photo.Random[]` when passing `count`, but it could also be updated to return either and leave it up to the developer to check the response type.

**Comment by OliverJAsh** [comment]
https://github.com/unsplash/unsplash-js/releases/tag/v7.0.11
