### ISSUE TITLE
Use content filter with getRandom?

### ISSUE THREAD

**Issue by nicholaschiang** [unsplash/unsplash-js#168]
Is there a way to use the `contentFilter` option with `unsplash.photos.getRandom()`? It's listed as a parameter in [the REST API documentation](https://unsplash.com/documentation#get-a-random-photo), but it isn't included in the TypeScript types for `getRandom`.

**Comment by OliverJAsh** [comment]
Thanks! Released in v.7.0.9. https://github.com/unsplash/unsplash-js/releases/tag/v7.0.9
