### ISSUE TITLE
Failed to load resource: the server responded with a status of 403 ()

### ISSUE THREAD

**Issue by deepakgudi-pixel** [unsplash/unsplash-js#175]
Getting an 403 error is it related to api request limit? how long should I wait?

**Comment by OliverJAsh** [comment]
If you were rate limited you would see a 429.

403 means forbidden. Most of the time this means you're using an invalid authentication token for the requested resource. In rare circumstances this could also mean your IP has been blocked.

**Comment by deepakgudi-pixel** [comment]
I see! thank you so much Oliver for clarifying my doubt!
