### ISSUE TITLE
Access Response headers from API calls

### ISSUE THREAD

**Issue by all-things-liquid** [unsplash/unsplash-js#176]
I recently upgraded to the 7.0.10 version of the package to get TypeScript typing. But I can't find a way to access response headers from API calls, since I only get an object of type ApiResponse<T>.

I need to get access to rate limit information inside my code, and used to be able to do that with the 6.3.0 version:

```
const remainingRequests = parseInt(response.headers._headers['x-ratelimit-remaining'][0])
const limitRequests = parseInt(response.headers._headers['x-ratelimit-limit'][0])
```

Is there another way I can have access to this?

**Comment by OliverJAsh** [comment]
With 170f07759390c840e655110a6c76da1627b72c71 you should be able to do this:

```ts
const api = createApi({ accessKey: 'MY_ACCESS_KEY' });
api.topics.get({ topicIdOrSlug: 'foo' }).then(apiResponse => {
  apiResponse.originalResponse.headers.get('content-type');
});
```

**Comment by OliverJAsh** [comment]
https://github.com/unsplash/unsplash-js/releases/tag/v7.0.11
