### ISSUE TITLE
collections.getPhotos api issue

### ISSUE THREAD

**Issue by youyiqin** [unsplash/unsplash-js#183]
#### Steps to Reproduce

- request collection.getPhotos with perPage: 100

#### Observed Behaviour

- just return 30 items,I am sure the size is large then 30.

> _Image or video please._

#### Expected Behaviour

- return correct size items

#### Technical Notes

- none

**Comment by OliverJAsh** [comment]
Please provide a fully working reduced test case that we can run, e.g. using CodeSandbox or Stackblitz.
