### ISSUE TITLE
Unable to build in nodejs typescript

### ISSUE THREAD

**Issue by odufuwa-segun** [unsplash/unsplash-js#187]
#### Steps to Reproduce

> yarn build

-

#### Observed Behaviour

Stack trace:

> Error: node_modules/unsplash-js/dist/beacon.d.ts(5,15): error TS2304: Cannot find name 'Response'.
> Error: node_modules/unsplash-js/dist/helpers/request.d.ts(4,33): error TS2304: Cannot find name 'RequestInit'.
> Error: node_modules/unsplash-js/dist/helpers/request.d.ts(8,70): error TS2304: Cannot find name 'RequestInit'.
> Error: node_modules/unsplash-js/dist/helpers/request.d.ts(12,60): error TS2304: Cannot find name 'RequestInit'.
> Error: node_modules/unsplash-js/dist/helpers/request.d.ts(25,20): error TS2304: Cannot find name 'fetch'.
> Error: node_modules/unsplash-js/dist/helpers/request.d.ts(26,16): error TS2304: Cannot find name 'RequestInit'.
> Error: node_modules/unsplash-js/dist/helpers/response.d.ts(5,23): error TS2304: Cannot find name 'Response'.
> Error: node_modules/unsplash-js/dist/helpers/response.d.ts(12,23): error TS2304: Cannot find name 'Response'.
> Error: node_modules/unsplash-js/dist/helpers/response.d.ts(17,15): error TS2304: Cannot find name 'Response'.
> Error: node_modules/unsplash-js/dist/helpers/response.d.ts(19,122): error TS2304: Cannot find name 'Response'.
> error Command failed with exit code 2.
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
> Error: Process completed with exit code 2.

-

> _Image or video please._

#### Expected Behaviour
Expect build to be successful

-

#### Technical Notes

- Node v14.17.6
- Typescript v4.2.3(fails on the latest too)

**Comment by OliverJAsh** [comment]
Please provide a reduced test case. Closing until this is provided.

**Comment by odufuwa-segun** [comment]
HI @OliverJAsh, I'm not too familiar with the term reduced test case, what am I to provide?

**Comment by OliverJAsh** [comment]
By reduced test case I mean something like a GitHub repository I can easily clone to reproduce the issue, in the smallest version you can provide.

**Comment by odufuwa-segun** [comment]
Hi @OliverJAsh, I have added the reduced test case.

**Comment by odufuwa-segun** [comment]
Hi @OliverJAsh, I have provided the reduced test case.

**Comment by odufuwa-segun** [comment]
Hi @OliverJAsh, I've fixed the issue.

I added the code below to my initialization script and that resolved the issue. My guess is that Request, RequestInnit and Response is defined as types with the fetch which for I guess wasn't globally set when I imported node-fetch.  The code just declares fetch, Request, RequestInit and Response as global.


`
import * as nodeFetch from 'node-fetch'
import { InitParams } from 'unsplash-js/dist/helpers/request';

declare global {
  var fetch: typeof nodeFetch.default;
  type RequestInit = nodeFetch.RequestInit;
  type Response = nodeFetch.Response;
}

`

**Comment by OliverJAsh** [comment]
Thank you!

This has come up a few times before:

- https://github.com/unsplash/unsplash-js/issues/186#issuecomment-951130928
- https://github.com/unsplash/unsplash-js/issues/166#issuecomment-801341405

… so I added some documentation here: b8867e9f95ed55421f3acb6cd37e5fb62708745c.

I raised a PR to fix your problem but it sounds like you figured it out!

https://github.com/odufuwa-segun/unsplash-backend-reduced-/pull/1
