### ISSUE TITLE
The doc is not clear about what will happen if I reach the rate limit

### ISSUE THREAD

**Issue by NE-SmallTown** [unsplash/unsplash-js#199]
#### Steps to Reproduce

- No need to provide

#### Observed Behaviour

- No need to provide

> _Image or video please._

#### Expected Behaviour

- No need to provide

#### Technical Notes

- At now, there is no doc or note about what the response/http status will be if I reach the rate limit

At https://github.com/unsplash/unsplash-js/issues/175 , @OliverJAsh  said the http status will be `429` if I reach the rate limit, but I can't find the related doc in https://unsplash.com/documentation

**Comment by NE-SmallTown** [comment]
@OliverJAsh  Can I ask that why there is no related doc describing it?

**Comment by OliverJAsh** [comment]
.@aaronklaassen would know, but if I had to guess I'd say it's because this is a widely used convention for HTTP APIs.
