### ISSUE TITLE
Search photos and Sorting

### ISSUE THREAD

**Issue by duyhung85** [unsplash/unsplash-js#29]
Hi,

Can I search photos and sort them at the same time?
E.g. I want to search "phone" photos and can be sorted by 'popular' or 'latest'

I can find the order_by parameter in unsplash.listPhotos() but not in unsplash.searchPhotos()

Thanks,

**Comment by lukechesser** [comment]
Hey @duyhung85, right now the API doesn't support that functionality. We'll look into adding that though — I'll chat with the team.

Closing for now until it's possible to support via the API.
