### ISSUE TITLE
unsplash.js:24 Uncaught ReferenceError: toJson is not defined(…)

### ISSUE THREAD

**Issue by concuacon** [unsplash/unsplash-js#32]

**Comment by mrmartineau** [comment]
For others that have been caught out by this, you also need to `import` toJson from the unsplash library, like so:

```js
import Unsplash, { toJson } from "unsplash-js";
```

Hope that helps. @joshwcomeau you should update the documentation.

**Comment by joshwcomeau** [comment]
@mrmartineau yeah, good call. Will update docs.

**Comment by mrmartineau** [comment]
@joshwcomeau will you add it to the docs in the readme? or elsewhere?

**Comment by samijaber** [comment]
@mrmartineau The docs already did mention the helper method (https://github.com/unsplash/unsplash-js#tojsonres), but I went ahead and updated the README with an explicit side-note about it at the top: https://github.com/unsplash/unsplash-js/commit/a67fd0d542a99795d32094f57b20a66b5a36e780

**Comment by jasonhargrove** [comment]
Document uses `toJson` everywhere but starting in the first code examples, does not include it. I did find it thanks to this thread, though it should be in the first example where it's a dep.

To those wondering what this "helper" does it's just this:

```
res.toJson()
```

Which is what the example should show.

For those into `async` here's what you need:

```
  const res = await unsplash.collections.listCollections(1, 100);
  const data = await res.json();
```
This and the fetch polyfill on the global is a touch awkward. Node module not intended for the browser, why not use `request`?

In any case the quick start is appreciated!
