### ISSUE TITLE
Get multiple photos by ID

### ISSUE THREAD

**Issue by scferg** [unsplash/unsplash-js#36]
Hey there,

Is it at all possible to query for multiple photos if I have an array of photo IDs? The only way I can think of currently is to loop through the desired photo IDs and do a `photos.getPhoto()` for each, which may be costly if the list of IDs gets long...

Could `search.photos()` perhaps also accept an array for the `keyword` parameter and also query by photo ID?

Thanks!

**Comment by JerryChin** [comment]
Good point, with regard to the limited rate of API request, this can be a headache.

**Comment by joshwcomeau** [comment]
Hi @scferg, @JerryChin.

Just spoke to our API team, and there are plans to add support for multi-photo lookup. Sadly, though, it's not likely to happen for a while. Until the API is updated, not much can be done for unsplash-js.

Wish I had better news! I'll leave the issue open, and update it when this functionality is implemented.

**Comment by scferg** [comment]
Thanks for chiming in @joshwcomeau!

I may have to inquire about getting an increased request cap then. 😉 

In my scenario of doing a loop through each photo ID, how taxing is it on your end to get, say, 40+ requests for `getPhoto()` at once? I certainly don't want to bog anything down or be flagged for abusing the API... If it'll be a problem, I'll just shelf the feature I need this for until the API is updated.

Thanks again!

**Comment by aaronklaassen** [comment]
@scferg Unless you've got a *lot* of users doing those 40 requests, our servers can handle it. If possible caching our json responses locally can go a long way, too.

If you've got other questions (or want to talk about increased rate limits) send me an email: api@unsplash.com 😎
