### ISSUE TITLE
Small collections not randomizing

### ISSUE THREAD

**Issue by pschfr** [unsplash/unsplash-js#41]
#### Steps to Reproduce
Use [Unsplash Source](https://source.unsplash.com/) to load a small collection, for example, [this one with 6 photos](https://unsplash.com/collections/585985/the-burgh). You should get a random one of those six, but I only get [one](https://unsplash.com/collections/585985/the-burgh?photo=ae4KypxWHr8) of those images?

**Comment by pschfr** [comment]
I also made an issue for this on [Unsplash Source JS](https://github.com/unsplash/unsplash-source-js/issues/14), as I was unsure where to put this...

**Comment by aaronklaassen** [comment]
https://github.com/unsplash/unsplash-source-js/issues/14#issuecomment-287454588
