### ISSUE TITLE
I keep getting TypeError: Unsplash is not a constructor

### ISSUE THREAD

**Issue by crod93** [unsplash/unsplash-js#42]
on const unsplash = new Unsplash({

**Comment by jzhangnu** [comment]
me too, same problem when using unsplash api in angular2

**Comment by onel0p3z** [comment]
@crod93 @jzhangnu are you certain that the lib has loaded successfully before using it? What browser,cdn,framework, etc. are you using?

**Comment by samijaber** [comment]
Make sure you are importing it correctly:

```js
//es6 imports syntax
import Unsplash from 'unsplash-js';

//requires syntax
var Unsplash = require('unsplash-js').default;
```

reference: https://stackoverflow.com/a/33705077

**Comment by Sunny4525** [comment]
//require syntax
var Unsplash = require('unsplash-js').default;
var Unsplash = require('unsplash-js');

I have used both but still no luck i am keep getting the same error and tried many way,
will you guys please help me out, i am working on node version 14.15.3 and npm version 6.14.9 and yes i have installed the unsplash-js lib.

**Comment by samijaber** [comment]
@Sunny4525 This issue is very outdated. See https://github.com/unsplash/unsplash-js/tree/2021d1eed92975447dc043271b14b6498cd48948#usage on how to import the library. There is no longer a default export
