### ISSUE TITLE
random photo from collection with id 1246235 returns  "errors": [     "No photos found."   ]

### ISSUE THREAD

**Issue by ankithjoseph** [unsplash/unsplash-js#49]
#### Steps to Reproduce
GET https://api.unsplash.com/photos/random?client_id='value'&count=10&collections=1246235
-

#### Expected Behaviour
check the collection with id 1246235 here https://unsplash.com/collections/1246235/   but not able to get it 
-
Any help on what i am doing wrong. Thank you.

**Comment by ankithjoseph** [comment]
I am able to get it work with different collection id eg:1173341

**Comment by Nick-the-BinaryTree** [comment]
I'm having the same issue. Is there any solution other than copying an existing collection to a different id?

**Comment by samijaber** [comment]
Tagging @unsplash/api as this is a backend issue
