### ISSUE TITLE
Relevance of search results

### ISSUE THREAD

**Issue by nikkwong** [unsplash/unsplash-js#50]
Hi, I realize that this is not a bug and more of a feature request/question, so apologies for that.

I have a slight concern about the relevance of the search results returned from ```getRandomImage```. For my specific use case, I need to get a picture of a city that I am querying by name. I.e. ```{query: denver}```. 

The problem obviously being that when anyone is tagging images with whatever they want, I don't really know what I'm going to get in my result. One particular example is Denver, a search here shows: https://unsplash.com/search/photos/denver
Picutres of lions, a cat, a car. 

Unsplash does not seem to support searching by unions of keys—for example, "denver city" will return images tagged ```denver``` and images tagged ```city```. 

In the perfect world, the return of that search result would be images that are tagged with a union of those search terms. 

I've also noticed that the first image in the results is typically pretty relevant. On the Unsplash UI, if I search for any major US city, I'm typically going to be returned a city of the skyline as the first result.

So the question is twofold: 1) Is it possible to add some kind of keyword unioning so I can take a city name, append 'city' to the search, i.e. ```denver city``` and reliably be returned a picture of that city? 2) If not, is it possible to just be returned the most relevant image, or first result? It seems that Unsplash has some internal ranking going on, but I can not be sure.

If neither of these is supported, how would one suggest I go about this? 

Thank you.

**Comment by aaronklaassen** [comment]
@nikkwong You're right that when selecting a random image from a search result, you'll get random levels of relevancy, and may not be what you're looking for. The lion, for example, is in the results for "Denver" because that's where it was taken.

Improving search results is of course an ongoing project for us. For now the behaviour you're seeing is expected, but it will continue to improve in the future.
