### ISSUE TITLE
Adding orientation as a parameter for /search/photos endpoint

### ISSUE THREAD

**Issue by Macksen** [unsplash/unsplash-js#55]
#### Request

Are there any plans to add **orientation** as a parameter to the search query?
I saw that this already exists and is available under _/photos/random_ endpoint but unfortunately not
under the _/search/photos_ endpoint.

It would be a great feature to implement to get more specific pictures, depending on what dimensions one needs.

**Comment by Macksen** [comment]
Seems to have been added now.

**Comment by shigg1120** [comment]
Hi @Macksen How did you do it? Can you paste the function please??

**Comment by Macksen** [comment]
@shigg1120 The GET request would look something like this for the search endpoint:

`https://api.unsplash.com/photos/search?client_id=CLIENT_ID&query=QUERY&orientation=ORIENTATION`

Valid values for orientation is the following: **landscape, portrait, and squarish**

**Comment by StadnykYura** [comment]
@Macksen , Orientation parameter doesn't work with https://api.unsplash.com/photos/search?....
When i put LANDSCAPE or PORTRAIT param, Response comes with both, portrait AND landscape photos, not with orientation i've asked. Can you pls check it?

**Comment by Macksen** [comment]
@StadnykYura Can I see your full request? Make sure to hide the access token/client id.

**Comment by StadnykYura** [comment]
@Macksen 
https://api.unsplash.com/search/photos?client_id=*********&query=animal&orientation=landscape

**Comment by StadnykYura** [comment]
@Macksen 
interesting, but today it seems to be working)

**Comment by danxczm** [comment]
hey guys, long time but it doesn’t work for me...
am i missing something?
`/search/photos?page=1&query=cat&orientation=landscape&client_id=...`
thanks for help in advance!
