### ISSUE TITLE
import Unsplash

### ISSUE THREAD

**Issue by epilkis** [unsplash/unsplash-js#57]
#### Steps to Reproduce
import Unsplash from 'unsplash-js';

const unsplash = new Unsplash({
  applicationId: "{APP_ID}",
  secret: "{APP_SECRET}",
  callbackUrl: "{CALLBACK_URL}"
});
-

#### Observed Behaviour
When running file with above content in node, the error is 
import Unsplash from 'unsplash-js';
SyntaxError: Unexpected token import

When running in Chrome browser, the error is
import Unsplash from 'unsplash-js';
"Uncaught syntax error: Unexpected Identifier"
-

> _Image or video please._

#### Expected Behaviour
The module imported successfuly as README example indicates it should
-

#### Technical Notes

-

**Comment by samijaber** [comment]
That's because we're using ES Modules syntax, which is not supported in node by default. I have updated the README to show an example using the standard `require` syntax [here](https://github.com/unsplash/unsplash-js/blob/master/README.md#creating-an-instance).
