### ISSUE TITLE
Response data

### ISSUE THREAD

**Issue by Shigeki1120** [unsplash/unsplash-js#65]
First of all, thanks for this awesome package👍

 This is rather a question.

Is there a situation when a response does not contain any of these `raw`, `thumb`, `small`, `regular`, `full` in `url` object as well as `name` and profile urls in `user` object when using `unsplash.search.photos()`?

I want to make sure if the data is always present or no.

**Comment by dimaboychev** [comment]
for search photos when I log the response the only thing i get is this:

```
Response {
  size: 0,
  timeout: 0,
  [Symbol(Body internals)]:
   { body:
      PassThrough {
        _readableState: [Object],
        readable: true,
        domain: null,
        _events: [Object],
        _eventsCount: 7,
        _maxListeners: undefined,
        _writableState: [Object],
        writable: true,
        allowHalfOpen: true,
        _transformState: [Object] },
     disturbed: false,
     error: null },
  [Symbol(Response internals)]:
   { url: 'https://api.unsplash.com/photos/search?query=bear&category=&page=1&per_page=1',
     status: 200,
     statusText: 'OK',
     headers: Headers { [Symbol(map)]: [Object] } } }
```

there is no data of the images which is sad :( tried the library for php and it the response contains what you need -- urls for images, id's, etc.
