### ISSUE TITLE
UMD example fails

### ISSUE THREAD

**Issue by 6r1d** [unsplash/unsplash-js#67]
#### Steps to Reproduce

I've updated main.js file in UMD example folder with my app credentials and launched the server.

I changed main.js file like that:

    var unsplash = new Unsplash.default({
        applicationId: "...Application ID...",
        secret: "...Secret key...",
        callbackUrl: "...Redirect URI..."
    });

    unsplash.users.profile("naoufal")
        .then(Unsplash.toJson)
        .then(function (json) {
            console.log(json);
        });

#### Observed Behaviour

I'm stuck with this error: OAuth error: The access token is invalid. I am not sure how to fix it.
Should I fill callback url field with redirect url from my app (unsplash.com/oauth/applications/...)?
Is this example up-to-date?

**Comment by yusufsiregar44** [comment]
same issue here

**Comment by mukeshcgs** [comment]
same issue

**Comment by lukechesser** [comment]
This is likely due to the wrong accessKey value. It's been clarified in https://github.com/unsplash/unsplash-js/pull/111
