### ISSUE TITLE
CORS Errors with HTML Canvas Elements

### ISSUE THREAD

**Issue by mjcampagna** [unsplash/unsplash-js#73]
I'm using the IMG src value (a URL to any given image on Unsplash), and attempting to load that into an HTML canvas element. This is working splendidly in Chrome, but only in Chrome. In other browsers, I'm getting these errors:

[Error] Origin http://127.0.0.1:1337 is not allowed by Access-Control-Allow-Origin.
[Error] Failed to load resource: Origin http://127.0.0.1:1337 is not allowed by Access-Control-Allow-Origin. (photo-1533577871619-310ff191dd40, line 0)
[Error] Cross-origin image load denied by Cross-Origin Resource Sharing policy.

Obviously, this is running on localhost. I get the same when running a test deployment from Heroku.

Is there anything I can do on my side to fix this? Or is this something to do with the CORS configuration on the Unsplash side, that I cannot control?

**Comment by flackjap** [comment]
Same problem here.

My app has a gallery where users can select a photo from Unsplash (among ther sources) and add it to canvas where they will be able to add texts, shapes, etc.

Is there any solution to this or should we first store (download) images on our servers and serve them with the same origin?

**Comment by Ronalses** [comment]
The same here,
When I try to load a collection I receive this response from the server.

![image](https://user-images.githubusercontent.com/20784993/45242493-a23d5f80-b2c6-11e8-9dc6-e26427ece8de.png)

**Comment by frangeris** [comment]
Hey @flackjap I'm having the same issue with a canvas, did you find any workaround?

thank you...

**Comment by lomeat** [comment]
as I see nobody could find the answer

**Comment by charliegroll** [comment]
I haven't tried it, but it seems this could be solved by storing each image in localStorage before adding it to the canvas:

https://developer.mozilla.org/en-US/docs/Web/HTML/CORS_enabled_image

**Comment by samijaber** [comment]
This issue is about images in HTML Canvas and therefore not specific to Unsplash. Closing.

**Comment by shanti2530** [comment]
@samijaber what is the recommended solution from  Unsplash around this? 

- Should I download and store the images on my server? 
- Are there any plans to enable CORS on the download links as per example [here](https://developer.mozilla.org/en-US/docs/Web/HTML/CORS_enabled_image)? 
- Anything else I should be considering?

**Comment by mtrabelsi** [comment]
@samijaber  this is definately an issue from unsplash not for canvas, you have to provide a proper way to use the image.

**Comment by camilosw** [comment]
This is an old issue but probably someone will find it while trying to solve this issue like me. Unsplash URL returns the header `access-control-allow-origin: *`, so it will work from any domain. In my case, I just set 'Anonymous' to the `crossOrigin` attribute of `img` as described in the link posted by @charliegroll.

```
const image = new Image();
image.crossOrigin = 'Anonymous';
image.src = 'https://images.unsplash.com/...';
image.addEventListener('load', () => {
  // loaded image
});
```
