### ISSUE TITLE
Orientation parameter

### ISSUE THREAD

**Issue by efeconirulez** [unsplash/unsplash-js#76]
Orientation parameter is added to the [API](https://unsplash.com/documentation#search-photos) but seems like we can't use it with this library, since there is no such parameter for the functions.

**Comment by maxnordlund** [comment]
I found this, which I believe resolves this issue (line 87):

https://github.com/unsplash/unsplash-js/blob/fa6d60fd710cfe615749f034a256adcd6b87702d/src/methods/photos.js#L79-L90

**Comment by emao** [comment]
Any updates on adding this as a search parameter?

**Comment by lukechesser** [comment]
This is supported in 6.0 #112
