### ISSUE TITLE
require syntax for toJson function

### ISSUE THREAD

**Issue by tkalejaiye** [unsplash/unsplash-js#81]
I noticed that there is no require syntax for the toJson function from the unsplash-js module. Is there any other way to include its functionality other writing code in ES6 and transpiling with Babel?

**Comment by alex-lushiku** [comment]
Try `const toJson = require("unsplash-js").toJson;`

**Comment by Zamy97** [comment]
Thank you @alex-lushiku  much!!

That was the line that I was missing and making my life miserable for a week. Now it works.

**Comment by tobyelliott** [comment]
> Try `const toJson = require("unsplash-js").toJson;`

This should be added to the documentation because it doesn't work without it.
