### ISSUE TITLE
unsplash.search.photos returns same photo every time

### ISSUE THREAD

**Issue by bogdancojocariu** [unsplash/unsplash-js#85]
It is more of a question, does `unsplash.search.photos` should return a random photo, or not?

#### Steps to Reproduce

```
unsplash.search
    .photos(uniqueQuery, 1, 1)
    .then(toJson)
```

Where `uniqueQuery` is the value from an input + Number(new Date());

#### Observed Behaviour
- For the same input value, I am receiving the same photo every time. It doesn't say in the documentation if the returned photo should be random or not, but maybe it is related to: https://github.com/unsplash/unsplash-js/issues/56

#### Expected Behaviour

- receive a random photo for the same query on different calls

#### Technical Notes

- experiencing the same behavior with: 
```
https://api.unsplash.com/search/photos?client_id=my_client_id&query=coffee&page=1&per_page=1&unique=12334k
```

**Comment by samijaber** [comment]
Nope, search is not expected to return random photos. We have a separate, random photo endpoint for that.
