### ISSUE TITLE
No images in response data

### ISSUE THREAD

**Issue by dimaboychev** [unsplash/unsplash-js#86]
#### Steps to Reproduce

unsplash.photos
  .searchPhotos('bear', undefined, 1, 1)
  .then(toJson)
  .then(json => {
    console.log(json);
  });

#### Observed Behaviour
`Response {
  size: 0,
  timeout: 0,
  [Symbol(Body internals)]:
   { body:
      PassThrough {
        _readableState: [Object],
        readable: true,
        domain: null,
        _events: [Object],
        _eventsCount: 7,
        _maxListeners: undefined,
        _writableState: [Object],
        writable: true,
        allowHalfOpen: true,
        _transformState: [Object] },
     disturbed: false,
     error: null },
  [Symbol(Response internals)]:
   { url: 'https://api.unsplash.com/photos/search?query=bear&category=&page=1&per_page=1',
     status: 200,
     statusText: 'OK',
     headers: Headers { [Symbol(map)]: [Object] } } }`

> _Image or video please._

#### Expected Behaviour

get urls or ids of images?
Sorry but what am I doing wrong? I'm not getting the images... I thought they should be in the json data.

**Comment by gardelin** [comment]
use unsplash.search.photos() instead of unsplash.photos.searchPhotos().

https://github.com/unsplash/unsplash-js#search

**Comment by pr1apus** [comment]
same problem here

**Comment by Liang-Dongxing** [comment]
What have you solved?

**Comment by armanbalani** [comment]
same problem

**Comment by lukechesser** [comment]
Do you have a valid API key?

**Comment by MarkedWarrior** [comment]
I'm having the same issue, any help?

**Comment by lukechesser** [comment]
@MarkedWarrior what version are you using?

**Comment by MarkedWarrior** [comment]
@lukechesser I'm using version 6.0.0 and this is how I'm configuring the instance:

<img width="846" alt="Screen Shot 2019-10-23 at 5 51 22 PM" src="https://user-images.githubusercontent.com/15189068/67437308-88400880-f5be-11e9-9005-6fd2752d207c.png">

I hide part of the Access Key.

**Comment by lukechesser** [comment]
Try removing the `options` key:

```js
global.fetch = fetch;
const Splash = require('unsplash-js').default;
const unsplash = new Splash({
  accessKey: "{APP_ACCESS_KEY}",
)};
```

**Comment by MarkedWarrior** [comment]
That options key is just a helper from the IDE telling me what is the accepted parameter, so there's actually nothing there.

**Comment by lukechesser** [comment]
@MarkedWarrior can you send me the email associated with your Unsplash account? I can try locally then

**Comment by MarkedWarrior** [comment]
@lukechesser it's ali.kazal11@gmail.com

**Comment by lukechesser** [comment]
@MarkedWarrior thanks. When I plug [your accessKey into the `examples/node/index.js` script that's on `master`](https://github.com/unsplash/unsplash-js/blob/master/examples/node/app.js#L5), it works:

![Screen+Recording+2019-10-25+at+12 30+PM](https://user-images.githubusercontent.com/808452/67588096-411f5800-f723-11e9-9539-918b8b3fa6ad.gif)

**Comment by MarkedWarrior** [comment]
@lukechesser this is really weird since I just redeployed and ran it again and it still returned 

`{"photos":{"size":0,"timeout":0}}`

Here's the call I'm making:

<img width="646" alt="Screen Shot 2019-10-25 at 12 37 12 PM" src="https://user-images.githubusercontent.com/15189068/67588792-fbfc2580-f724-11e9-91f8-dcf8b79ef9e3.png">

**Comment by lukechesser** [comment]
@MarkedWarrior what happens though when you run the node script? (make sure to pull the latest version of master)

**Comment by MarkedWarrior** [comment]
@lukechesser I don't know exactly how to install it but I can try if it's really necessary. Let me know if you want me to and I'll give it a shot.

**Comment by MarkedWarrior** [comment]
@lukechesser I just ran the module (master) and the results were all there so I really don't understand why it isn't working for me :/

**Comment by lukechesser** [comment]
@MarkedWarrior Gotcha, thanks for trying it.

Can you copy the code you're using into a gist or something and share? I can't debug it without a reproducible case. My email is luke@unsplash.com if you'd prefer to share it there

**Comment by MarkedWarrior** [comment]
@lukechesser would a gist work for firebase functions?

**Comment by lukechesser** [comment]
So long as you can share the code, it should

**Comment by MarkedWarrior** [comment]
Hey @lukechesser , 
I added you as a collaborator to the gist. Please do let me know if you need anything else.

Thank you

**Comment by lukechesser** [comment]
Posting this here for everyone else who comes across it: https://github.com/unsplash/unsplash-js/issues/120#issuecomment-547639865

**Comment by jasonhargrove** [comment]
Somewhere on the page there is a description of a `toJson` helper. It's a `fetch` design returning a body with a function `json` that needs to be called as middleware. 

```
  const res = await unsplash.collections.listCollections(1, 100);
  const data = await res.json();
```
