### ISSUE TITLE
Random image call always returning the same image

### ISSUE THREAD

**Issue by clayostrom** [unsplash/unsplash-js#87]
#### Steps to Reproduce

I've run into an issue where my api call to photos/random always returns the same image. Previously this call had worked to return a different/random image on each call. 

An example of the call I'm using is:
https://api.unsplash.com/photos/random/?query=books&client_id=myapikey

I've also experimented with adding a count parameter and in this case it seems to always return the same array of photos.

#### Observed Behaviour

I initially noticed this behavior in my app, but when testing the call in the browser I also see that it's returning the same image every time from this call.

Has this method changed or is this an issue on the Unsplash side?

**Comment by lukechesser** [comment]
I think this was a temporary issue on the API side. Closing for now, but let us know if it's still happening. Thanks!
