### ISSUE TITLE
How to save photo to local disk for use

### ISSUE THREAD

**Issue by DavidFCHW** [unsplash/unsplash-js#96]
#### Steps to Reproduce

- Is there any way that I can save a photo to my local directories, at the moment the downloadPhoto() function returns a response, which does contain a url, however the url gives the following error:
{"errors":["OAuth error: The access token is invalid"]}
How do I get the donwload link to save the photo locally?
 
(The app won't be published publicly, it's for a University project). 
unsplash.search.photos("Blessed", 1).then(toJson).then(json => {

    unsplash.photos.downloadPhoto(json.results[0]).then(photo => {
        console.log(photo);
    }).catch(error => {
        console.log(error);
    });
}).catch(error => {
    console.log('Could not find photo on Unpslash.');
});

#### Observed Behaviour

- Response {
  size: 0,
  timeout: 0,
  [Symbol(Body internals)]:
   { body:
      PassThrough {
        _readableState: [ReadableState],
        readable: true,
        _events: [Object],
        _eventsCount: 2,
        _maxListeners: undefined,
        _writableState: [WritableState],
        writable: false,
        allowHalfOpen: true,
        _transformState: [Object] },
     disturbed: false,
     error: null },
  [Symbol(Response internals)]:
   { url: 'https://api.unsplash.com/photos/-S-OKXUfFjA/download?',
     status: 200,
     statusText: 'OK',
     headers: Headers { [Symbol(map)]: [Object] },
     counter: 0 } }

> _Image or video please._

#### Expected Behaviour

-

#### Technical Notes

-

**Comment by Dayjo** [comment]
Hi @DavidFCHW 

As far as I have understood from the documentation, the `downloadPhoto` method is actually a `trackDownload` method and is used only for Unsplash's analytics. 

To download the file locally, you'll need to use `fetch` or `curl` or something to get it from one of the URLs supplied by the API in the Photo object

**Comment by garvitsharma05** [comment]
Hey if you solved that doubt, please acknowledge me too. How to download from Api part.

**Comment by lukechesser** [comment]
@garvitsharma05 the API makes the images available as remote URLs. Google how to write a remote URL to your local disk, like https://stackoverflow.com/questions/19237460/node-js-request-saving-a-remote-file-and-serving-it-in-a-response
