### ISSUE TITLE
TypeError [ERR_UNESCAPED_CHARACTERS]: Request path contains unescaped characters

### ISSUE THREAD

**Issue by lelikg** [unsplash/unsplash-js#99]
#### Steps to Reproduce
invoke "searchPhotos" with non-latin chars, for example Cyrillic "ааа"
-

#### Observed Behaviour
TypeError [ERR_UNESCAPED_CHARACTERS]: Request path contains unescaped characters
    at new ClientRequest (_http_client.js:115:13)
    at request (https.js:281:10)
    .....
-

> _Image or video please._

#### Expected Behaviour
Query should be escaped when building the url within unsplashJS sdk
-

#### Technical Notes

-

**Comment by lukechesser** [comment]
Fixed in #119 and will be released in #112
